CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CITY VARCHAR(100) NOT NULL);



CREATE TABLE PRODUCTS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    STOCK INT CHECK (STOCK >0),
    PRICE DECIMAL(10,2) CHECK (PRICE >0));



CREATE TABLE ORDERS(
    ID SERIAL PRIMARY KEY,
    UID INT REFERENCES users(ID) ON DELETE CASCADE,
    PID INT REFERENCES products(ID) ON DELETE CASCADE,
    QUANTITY INT CHECK (QUANTITY >0),
    TOTAL_AMOUNT DECIMAL(10,2),
    STATUS VARCHAR(100) DEFAULT 'PENDING');