SELECT * FROM USERS;

<<<<<<< HEAD
SELECT * FROM ORDERS;

SELECT * FROM PRODUCTS;


SELECT * FROM USERS 
WHERE CITY = 'Delhi';

SELECT * FROM PRODUCTS
WHERE PRICE >= 12000.00;

SELECT * FROM PRODUCTS
WHERE STOCK >= 10 AND PRICE >= 3000.00;


SELECT * FROM PRODUCTS
WHERE STOCK >= 10 OR PRICE >= 3000.00;


SELECT * FROM ORDERS
WHERE STATUS = 'COMPLETED';

SELECT * FROM USERS;
SELECT * FROM ORDERS;


SELECT U.NAME, U.CITY, O.STATUS
FROM USERS AS U
INNER JOIN ORDERS AS O
ON U.ID = O.ID;


SELECT U.NAME, U.CITY , O.TOTAL_AMOUNT
FROM USERS AS U
INNER JOIN ORDERS AS O
ON U.ID = O.ID
WHERE O.TOTAL_AMOUNT >= 9000.00
ORDER BY  O.TOTAL_AMOUNT DESC
LIMIT 3;

SELECT P.NAME, O.QUANTITY, O.STATUS
FROM PRODUCTS AS P
JOIN ORDERS AS O
ON P.ID = O.PID;

SELECT P.NAME, O.QUANTITY, O.STATUS
FROM PRODUCTS AS P
JOIN ORDERS AS O
ON P.ID = O.PID
WHERE STATUS = 'COMPLETED';

SELECT U.NAME, SUM(O.TOTAL_AMOUNT) AS TOTAL_SPEND
FROM USERS AS U
JOIN ORDERS AS O
ON U.ID = O.UID
GROUP BY U.NAME;

SELECT P.NAME, SUM(O.QUANTITY) AS TOTAL_SOLD
FROM PRODUCTS AS P
INNER JOIN ORDERS AS O
ON P.ID = O.PID
GROUP BY P.NAME
ORDER BY TOTAL_SOLD DESC;

SELECT P.NAME, SUM(O.QUANTITY) AS TOTAL_SOLD
FROM PRODUCTS AS P
INNER JOIN ORDERS AS O
ON O.PID = P.ID
GROUP BY P.NAME
ORDER BY TOTAL_SOLD DESC;


SELECT P.NAME, SUM(O.QUANTITY) AS TOTAL_SOLD
FROM PRODUCTS AS P
JOIN ORDERS AS O
ON P.ID = O.PID
GROUP BY P.NAME
ORDER BY TOTAL_SOLD DESC
LIMIT 3;

SELECT P.NAME, SUM(O.QUANTITY) AS TOTAL_SOLD
FROM PRODUCTS AS P
JOIN ORDERS AS O
ON P.ID = O.PID
GROUP BY P.NAME
ORDER BY TOTAL_SOLD DESC
LIMIT 3 OFFSET 2;

SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM USERS;

SELECT P.NAME , SUM(O.TOTAL_AMOUNT) AS REVENUE
FROM PRODUCTS AS P
JOIN ORDERS AS O
ON P.ID = O.PID
GROUP BY P.NAME
ORDER BY REVENUE DESC ;


SELECT U.NAME , COUNT(O.ID) AS ORDER_COUNT
FROM USERS AS U
JOIN ORDERS AS O
ON U.ID = O.UID
GROUP BY U.NAME
HAVING  COUNT(O.ID) >= 1
ORDER BY ORDER_COUNT DESC
LIMIT 5;

INSERT INTO ORDERS (UID, PID, QUANTITY, TOTAL_AMOUNT, STATUS)
VALUES
(1,2,2,1000,'PENDING'),
(1,3,3,1200,'PENDING'),
(2,4,2,15000,'SHIPPED'),
(2,5,3,10000,'SHIPPED');

SELECT U.NAME , COUNT(O.ID) AS ORDER_COUNT
FROM USERS AS U
JOIN ORDERS AS O
ON U.ID = O.UID
GROUP BY U.NAME
HAVING  COUNT(O.ID) > 1
ORDER BY ORDER_COUNT DESC
LIMIT 3 ;

SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM USERS;

SELECT 
	U.NAME AS USER_NAME,
	U.CITY AS USER_CITY,
	P.NAME AS PRODUCT_NAME,
	P.PRICE AS PRODUCT_PRICE,
	O.QUANTITY AS TOTAL_QUANTITY,
	O.TOTAL_AMOUNT AS TOTAL_PRICE,
	O.STATUS AS ORDER_STATUS
FROM USERS AS U
JOIN ORDERS AS O
ON U.ID = O.UID
JOIN PRODUCTS AS P
ON P.ID = O.PID;
	




=======
SELECT * FROM PRODUCTS;

SELECT * FROM ORDERS;

SELECT *
FROM ORDERS
WHERE STATUS = 'COMPLETED';

SELECT NAME,STOCK
FROM PRODUCTS
WHERE STOCK > 10;

SELECT NAME, STOCK,PRICE
FROM PRODUCTS
WHERE STOCK >= 10 AND PRICE >= 18000.00;

SELECT NAME
FROM USERS
WHERE NAME LIKE 'A%';

SELECT NAME
FROM USERS
WHERE NAME LIKE '%a';

SELECT *
FROM USERS
WHERE CITY = 'Delhi';

SELECT *
FROM ORDERS
WHERE TOTAL_AMOUNT >= 5000.00;

UPDATE USERS
SET CITY = 'Delhi'
WHERE ID = 5;
>>>>>>> 80f85cd (add queries.sql)



